// ==========================================
// DATA
// ==========================================

export interface VocabularyItem {
    katakana: string;
    answer: string;
    alternates?: string[];
}

export const VOCABULARY: VocabularyItem[] = [
    { katakana: 'バットマン', answer: 'batman' },
    { katakana: 'スーパーマン', answer: 'superman' },
    { katakana: 'ピアノ', answer: 'piano' },
    { katakana: 'サッカー', answer: 'soccer' },
    { katakana: 'テニス', answer: 'tennis' },
    { katakana: 'ゴルフ', answer: 'golf' },
    { katakana: 'アイスクリーム', answer: 'ice cream', alternates: ['icecream'] },
    { katakana: 'バナナ', answer: 'banana' },
    { katakana: 'オレンジ', answer: 'orange', alternates: ['orangey'] },
    { katakana: 'トマト', answer: 'tomato' },
    { katakana: 'コンピューター', answer: 'computer' },
    { katakana: 'インターネット', answer: 'internet' },
    { katakana: 'メール', answer: 'mail', alternates:['mare'] },
    { katakana: 'ハンバーガー', answer: 'hamburger' },
    { katakana: 'ピザ', answer: 'pizza' },
    { katakana: 'チーズ', answer: 'cheese' },
    { katakana: 'ベーコン', answer: 'bacon' },
    { katakana: 'ベーコンチーズバーガー', answer: 'bacon cheese burger' },
    { katakana: 'ビール', answer: 'beer' },
    { katakana: 'ワイン', answer: 'wine', alternates: ['whine'] },
    { katakana: 'ジュース', answer: 'juice' },
    { katakana: 'ティー', answer: 'tea' },
    { katakana: 'ミルク', answer: 'milk' },
    { katakana: 'ステーキ', answer: 'steak' },
    { katakana: 'ダンス', answer: 'dance' },
    { katakana: 'ギター', answer: 'guitar' },
    { katakana: 'マイク', answer: 'mic' },
    { katakana: 'ペン', answer: 'pen' },
    { katakana: 'デスク', answer: 'desk' },
    { katakana: 'カメラ', answer: 'camera' },
    { katakana: 'ビデオ', answer: 'video' },
    { katakana: 'ラジオ', answer: 'radio' },
    { katakana: 'ボタン', answer: 'button' },
    { katakana: 'エレベーター', answer: 'elevator' },
    { katakana: 'ドア', answer: 'door' },
    { katakana: 'ウィンドウ', answer: 'window' },
    { katakana: 'グラス', answer: 'glass', alternates: ['grass'] },
    { katakana: 'ガラス', answer: 'glass', alternates: ['grass'] },
    { katakana: 'スプーン', answer: 'spoon' },
    { katakana: 'フォーク', answer: 'fork', alternates: ['fog', 'fuck'] },
    { katakana: 'ナイフ', answer: 'knife' },
    { katakana: 'バス', answer: 'bus', alternates: ['boss', 'bath'] },
    { katakana: 'バイク', answer: 'bike' },
    { katakana: 'ウェブサイト', answer: 'website', alternates: ['web site'] },
    { katakana: 'ホテル', answer: 'hotel' },
    { katakana: 'レストラン', answer: 'restaurant' },
    { katakana: 'テーブル', answer: 'table' },
    { katakana: 'サービス', answer: 'service' },
    { katakana: 'サイズ', answer: 'size' },
    { katakana: 'シャツ', answer: 'shirt', alternates: ['shirts', 'shot', 'shots'] },
    { katakana: 'ネクタイ', answer: 'necktie' },
    { katakana: 'サンダル', answer: 'sandal' },
    { katakana: 'サングラス', answer: 'sunglass', alternates: ['sunglasses'] },
    { katakana: 'テスト', answer: 'test' },
    { katakana: 'サラリーマン', answer: 'salaryman', alternates: ['salary man'] },
    { katakana: 'ドライブ', answer: 'drive' },
    { katakana: 'ノック', answer: 'knock' },
    { katakana: 'キャンセル', answer: 'cancel' },
    { katakana: 'ジョギング', answer: 'jogging' },
    { katakana: 'リラックス', answer: 'relax', alternates: ['lilacs'] },
    { katakana: 'ジャンプ', answer: 'jump' },
    { katakana: 'キス', answer: 'kiss' },
    { katakana: 'メイク', answer: 'make', alternates: ['makeup'] },
    { katakana: 'パーティー', answer: 'party', alternates: ['pate', 'potty'] },
    { katakana: 'ギャンブル', answer: 'gamble' },
    { katakana: 'アップル', answer: 'apple' },
    { katakana: 'ウォーターメロン', answer: 'watermelon' },
    { katakana: 'スターバックス', answer: 'starbucks' },
    { katakana: 'ケンタッキー', answer: 'kentucky', alternates: ['kfc'] },
    { katakana: 'マクドナルド', answer: 'mcdonalds', alternates: ['mcdonald'] },
    { katakana: 'タイプ', answer: 'type' },
    { katakana: 'エンジン', answer: 'engine' },
    { katakana: 'カレンダー', answer: 'calendar' },
    { katakana: 'トンネル', answer: 'tunnel' },
    { katakana: 'マッチ', answer: 'match' },
    { katakana: 'ミシン', answer: 'machine', alternates: ['mission'] },
    { katakana: 'バー', answer: 'bar' },
    { katakana: 'スタイル', answer: 'style' },
    { katakana: 'ストーリー', answer: 'story' },
    { katakana: 'スマート', answer: 'smart' },
    { katakana: 'アイドル', answer: 'idol' },
    { katakana: 'アニメ', answer: 'anime', alternates: ['animation'] },
    { katakana: 'バター', answer: 'butter', alternates: ['batter'] },
    { katakana: 'バーゲン', answer: 'bargain' },
    { katakana: 'ドラマ', answer: 'drama' },
    { katakana: 'フライ', answer: 'fry', alternates: ['fly', 'fried'] },
    { katakana: 'フロント', answer: 'front' },
    { katakana: 'ハンドル', answer: 'handle' },
    { katakana: 'イメージ', answer: 'image' },
    { katakana: 'アメリカ', answer: 'america' },
    { katakana: 'イタリア', answer: 'italy', alternates: ['italia'] },
    { katakana: 'ホランダ', answer: 'holland', alternates: ['netherlands', 'the netherlands'] },
    { katakana: 'カナダ', answer: 'canada' },
    { katakana: 'スペイン', answer: 'spain' },
    { katakana: 'フランス', answer: 'france' },
    { katakana: 'スキー', answer: 'ski' },
    { katakana: 'スケート', answer: 'skate' },
    { katakana: 'パーティー', answer: 'party' },
    { katakana: 'バスケット', answer: 'basketball', alternates: ['basket'] },
    { katakana: 'ボウリング', answer: 'bowling' },
    { katakana: 'フライドポテト', answer: 'fried potato', alternates: ['french fries', 'fries', 'chips', 'friedpotato'] },
    { katakana: 'ホットケーキ', answer: 'hotcake', alternates: ['pancake'] },
    { katakana: 'ジーンズ', answer: 'jeans' },
    { katakana: 'スニーカー', answer: 'sneaker' },
    { katakana: 'ブレザー', answer: 'blazer', alternates: ['brazer', 'braiser'] },
    { katakana: 'ハンカチ', answer: 'handkerchief', alternates: ['hankie', 'hankerchief'] },
    { katakana: 'タクシー', answer: 'taxi' },
    { katakana: 'トラック', answer: 'truck', alternates:['track'] },
    { katakana: 'スクール', answer: 'school' },
    { katakana: 'プリンター', answer: 'printer' },
    { katakana: 'スキャナー', answer: 'scanner' },
    { katakana: 'モニター', answer: 'monitor' },
    { katakana: 'キーボード', answer: 'keyboard' },
    { katakana: 'マウス', answer: 'mouse' },
    { katakana: 'レンタル', answer: 'rental' },
    { katakana: 'シャンプー', answer: 'shampoo' },
    { katakana: 'コンディショナー', answer: 'conditioner' },
    { katakana: 'タオル', answer: 'towel' },
    { katakana: 'シート', answer: 'seat', alternates: ['sheet', 'shit'] },
    { katakana: 'ピッチ', answer: 'pitch', alternates: ['peach'] },
    { katakana: 'クッション', answer: 'cushion' },
    { katakana: 'カーテン', answer: 'curtain', alternates: ['carton'] },
    { katakana: 'ベッド', answer: 'bed' },
    { katakana: 'ソファ', answer: 'sofa' },
    { katakana: 'チェア', answer: 'chair' },
    { katakana: 'テーブル', answer: 'table' },
    { katakana: 'キャビネット', answer: 'cabinet' },
    { katakana: 'ドア', answer: 'door', alternates: ['doer'] },
    { katakana: 'プレート', answer: 'plate' },
    { katakana: 'ボウル', answer: 'bowl', alternates: ['ball'] },
    { katakana: 'カップ', answer: 'cup', alternates: ['cop'] },
    { katakana: 'ティーンエージャー', answer: 'teenager' },
    { katakana: 'スケルトン', answer: 'skeleton' },
    { katakana: 'ピクニック', answer: 'picnic' },
    { katakana: 'ベジタリアン', answer: 'vegetarian' },
    { katakana: 'エスケープ', answer: 'escape' },
    { katakana: 'トレーニング', answer: 'training' },
    { katakana: 'メモリー', answer: 'memory' },
    { katakana: 'マイ バット イズ ソー イッチー', answer: 'My butt is so itchy' },
    { katakana: 'アーカイブ', answer: 'archive' },
    { katakana: 'リユース', answer: 'reuse' },
    { katakana: 'リサイクルショップ', answer: 'recycling shop', alternates: ['recycle shop'] },
    { katakana: 'ブランド', answer: 'brand', alternates: ['bland'] },
    { katakana: 'フリーマーケット', answer: 'flea market', alternates: ['free market'] },
    { katakana: 'ロープウェー', answer: 'ropeway' },
    { katakana: 'マンガ', answer: 'manga' },
    { katakana: 'スシ', answer: 'sushi' },
    { katakana: 'トウフ', answer: 'tofu' },
    { katakana: 'スウドク', answer: 'sudoku' },
    { katakana: 'ボンサイ', answer: 'bonsai' },
    { katakana: 'テンプラ', answer: 'tempura' },
    { katakana: 'ラーメン', answer: 'ramen' },
    { katakana: 'カラオケ', answer: 'karaoke' },
    { katakana: 'ニンジャ', answer: 'ninja' },
    { katakana: 'サムライ', answer: 'samurai' },
    { katakana: 'キモノ', answer: 'kimono' },
    { katakana: 'フトン', answer: 'futon' },
    { katakana: 'オリガミ', answer: 'origami' },
    { katakana: 'エダマメ', answer: 'edamame' },
    { katakana: 'ミソ', answer: 'miso' },
    { katakana: 'テリヤキ', answer: 'teriyaki' },
    { katakana: 'ワサビ', answer: 'wasabi' },
    { katakana: 'サケ', answer: 'sake' },
    { katakana: 'ヒバチ', answer: 'hibachi' },
    { katakana: 'タタミ', answer: 'tatami' },
    { katakana: 'ゼン', answer: 'zen' },
    { katakana: 'ハイク', answer: 'haiku' },
    { katakana: 'エモジ', answer: 'emoji' },
    { katakana: 'オタク', answer: 'otaku' },
    { katakana: 'ツナミ', answer: 'tsunami' },
    { katakana: 'カラテ', answer: 'karate' },
    { katakana: 'ジュウドウ', answer: 'judo' },
    { katakana: 'スモウ', answer: 'sumo' },
    { katakana: 'マッチャ', answer: 'matcha' },
    { katakana: 'ウドン', answer: 'udon' },
    { katakana: 'ソバ', answer: 'soba' },
    { katakana: 'ギョウザ', answer: 'gyoza' },
    { katakana: 'サシミ', answer: 'sashimi' },
    { katakana: 'ウマミ', answer: 'umami' },
    { katakana: 'コイ', answer: 'koi' },
    { katakana: 'シアツ', answer: 'shiatsu' },
    { katakana: 'アイキドウ', answer: 'aikido' },
    { katakana: 'ケンドウ', answer: 'kendo' },
    { katakana: 'パンコ', answer: 'panko' },
    { katakana: 'ヤキソバ', answer: 'yakisoba' },
    { katakana: 'ニギリ', answer: 'nigiri' },
    { katakana: 'マキ', answer: 'maki' },
    { katakana: 'ワギュウ', answer: 'wagyu' },
    { katakana: 'カブキ', answer: 'kabuki' },
    { katakana: 'ゲイシャ', answer: 'geisha' },
    { katakana: 'リキシャ', answer: 'rickshaw' },
    { katakana: 'タイクーン', answer: 'tycoon' },
    { katakana: 'サヨナラ', answer: 'sayonara' },
    { katakana: 'バンザイ', answer: 'banzai' },
    { katakana: 'ポケモン', answer: 'pokemon' },
    { katakana: 'ニンテンドウ', answer: 'nintendo' },
    { katakana: 'ショウグン', answer: 'shogun' },
    { katakana: 'カタナ', answer: 'katana' },
    { katakana: 'ロウニン', answer: 'ronin' },
    { katakana: 'センセイ', answer: 'sensei' },
    { katakana: 'ドウジョウ', answer: 'dojo' },
    { katakana: 'カミカゼ', answer: 'kamikaze' },
    { katakana: 'セップク', answer: 'seppuku' },
    { katakana: 'カワイイ', answer: 'kawaii' },
    { katakana: 'ヒキコモリ', answer: 'hikikomori' },
    { katakana: 'タマゴッチ', answer: 'tamagotchi' },
    { katakana: 'シイタケ', answer: 'shiitake' },
    { katakana: 'ダイコン', answer: 'daikon' },
    { katakana: 'モチ', answer: 'mochi' },
    { katakana: 'ヤキトリ', answer: 'yakitori' },
    { katakana: 'タコヤキ', answer: 'takoyaki' },
    { katakana: 'イザカヤ', answer: 'izakaya' },
    { katakana: 'ベントウ', answer: 'bento' },
    { katakana: 'オニギリ', answer: 'onigiri' },
    { katakana: 'センパイ', answer: 'senpai' },
    { katakana: 'ヤクザ', answer: 'yakuza' },
    { katakana: 'ハローキティ', answer: 'hello kitty' },
    { katakana: 'ゴジラ', answer: 'godzilla' },
    { katakana: 'ピカチュウ', answer: 'pikachu' },
    { katakana: 'カイジュウ', answer: 'kaiju' },
    { katakana: 'ジブリ', answer: 'ghibli' },
];

export interface CharacterInfo {
    romaji: string;
    hiragana: string;
    katakana: string;
}

export const CHARACTERS: CharacterInfo[] = ([
    ["A","あ","ア"],["I","い","イ"],["U","う","ウ"],["E","え","エ"],["O","お","オ"],
    ["KA","か","カ"],["KI","き","キ"],["KU","く","ク"],["KE","け","ケ"],["KO","こ","コ"],
    ["SA","さ","サ"],["SHI","し","シ"],["SU","す","ス"],["SE","せ","セ"],["SO","そ","ソ"],
    ["TA","た","タ"],["CHI","ち","チ"],["TSU","つ","ツ"],["TE","て","テ"],["TO","と","ト"],
    ["NA","な","ナ"],["NI","に","ニ"],["NU","ぬ","ヌ"],["NE","ね","ネ"],["NO","の","ノ"],
    ["HA","は","ハ"],["HI","ひ","ヒ"],["FU","ふ","フ"],["HE","へ","ヘ"],["HO","ほ","ホ"],
    ["MA","ま","マ"],["MI","み","ミ"],["MU","む","ム"],["ME","め","メ"],["MO","も","モ"],
    ["YA","や","ヤ"],["YU","ゆ","ユ"],["YO","よ","ヨ"],
    ["RA","ら","ラ"],["RI","り","リ"],["RU","る","ル"],["RE","れ","レ"],["RO","ろ","ロ"],
    ["WA","わ","ワ"],["WO","を","ヲ"],
    ["N","ん","ン"],
    ["GA","が","ガ"],["GI","ぎ","ギ"],["GU","ぐ","グ"],["GE","げ","ゲ"],["GO","ご","ゴ"],
    ["ZA","ざ","ザ"],["JI","じ","ジ"],["ZU","ず","ズ"],["ZE","ぜ","ゼ"],["ZO","ぞ","ゾ"],
    ["DA","だ","ダ"],["DI","ぢ","ヂ"],["DU","づ","ヅ"],["DE","で","デ"],["DO","ど","ド"],
    ["BA","ば","バ"],["BI","び","ビ"],["BU","ぶ","ブ"],["BE","べ","ベ"],["BO","ぼ","ボ"],
    ["PA","ぱ","パ"],["PI","ぴ","ピ"],["PU","ぷ","プ"],["PE","ぺ","ペ"],["PO","ぽ","ポ"],
    ["ya","ゃ","ャ"],["yu","ゅ","ュ"],["yo","ょ","ョ"],
    ["a","ぁ","ァ"],["i","ぃ","ィ"],["u","ぅ","ゥ"],["e","ぇ","ェ"],["o","ぉ","ォ"],
    ["'","っ","ッ"],
    ["-","ー","ー"],
] as [string, string, string][]).map(arr => ({romaji: arr[0], hiragana: arr[1], katakana: arr[2]}));

export const ROMAJI_LOOKUP: Record<string, string> = Object.fromEntries(CHARACTERS.flatMap(d => [[d.katakana, d.romaji], [d.hiragana, d.romaji]]));
export const KATAKANA_LOOKUP: Record<string, string> = Object.fromEntries(CHARACTERS.flatMap(d => [[d.romaji, d.katakana], [d.hiragana, d.katakana]]));
export const HIRAGANA_LOOKUP: Record<string, string> = Object.fromEntries(CHARACTERS.flatMap(d => [[d.romaji, d.hiragana], [d.katakana, d.hiragana]]));

export const KATAKANA_GRID_STR = [
    "アイウエオ",
    "カキクケコ",
    "サシスセソ",
    "タチツテト",
    "ナニヌネノ",
    "ハヒフヘホ",
    "マミムメモ",
    "ヤ ユ ヨ",
    "ラリルレロ",
    "ワ   ヲ",
    "ン",
    "",
    "ガギグゲゴ",
    "ザジズゼゾ",
    "ダヂヅデド",
    "バビブベボ",
    "パピプペポ"
];

export interface GridCell {
    kana: string;
    romaji: string;
}

export const KATAKANA_GRID: (GridCell | null)[][] = KATAKANA_GRID_STR.map(row => row ? row.split('').map(kana => ((kana===' ')? null : {kana: kana, romaji:ROMAJI_LOOKUP[kana]})) : [null, null, null, null, null]);
export const HIRAGANA_GRID: (GridCell | null)[][] = KATAKANA_GRID.map(row => row.map(cell => (cell===null) ? null : {kana:HIRAGANA_LOOKUP[cell.kana], romaji:cell.romaji}))

export interface KanaGroup {
    id: string;
    name: string;
    kana: string[];
}

export const KANA_GROUPS: KanaGroup[] = [
    { id: 'a', name: 'a', kana: ['ア', 'イ', 'ウ', 'エ', 'オ'] },
    { id: 'ka', name: 'ka', kana: ['カ', 'キ', 'ク', 'ケ', 'コ'] },
    { id: 'sa', name: 'sa', kana: ['サ', 'シ', 'ス', 'セ', 'ソ'] },
    { id: 'ta', name: 'ta', kana: ['タ', 'チ', 'ツ', 'テ', 'ト'] },
    { id: 'na', name: 'na', kana: ['ナ', 'ニ', 'ヌ', 'ネ', 'ノ'] },
    { id: 'ha', name: 'ha', kana: ['ハ', 'ヒ', 'フ', 'ヘ', 'ホ'] },
    { id: 'ma', name: 'ma', kana: ['マ', 'ミ', 'ム', 'メ', 'モ'] },
    { id: 'ya', name: 'ya', kana: ['ヤ', 'ユ', 'ヨ'] },
    { id: 'ra', name: 'ra', kana: ['ラ', 'リ', 'ル', 'レ', 'ロ'] },
    { id: 'wa', name: 'wa', kana: ['ワ', 'ヲ'] },
    { id: 'n', name: 'n', kana: ['ン'] },
    { id: 'others', name: 'curiosities', kana: [
        'ガ', 'ギ', 'グ', 'ゲ', 'ゴ',
        'ザ', 'ジ', 'ズ', 'ゼ', 'ゾ',
        'ダ', 'ヂ', 'ヅ', 'デ', 'ド',
        'バ', 'ビ', 'ブ', 'ベ', 'ボ',
        'パ', 'ピ', 'プ', 'ペ', 'ポ',
        'ッ', 'ー', 'ァ', 'ィ', 'ゥ', 'ェ', 'ォ', 'ャ', 'ュ', 'ョ'
    ] }
];

export type TestMode = 'words' | 'kana' | 'both';

export interface QuizSettings {
    useHiragana: boolean;
    selectedGroups: string[];
    testMode: TestMode;
}
